
package com.ocb.ttt.esb.payment;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PaymentExecution", targetNamespace = "http://bian.com.vn/PaymentExecution/", wsdlLocation = "http://10.96.23.111:8800/paymentexecution/v1/ws?wsdl")
public class PaymentExecution_Service
    extends Service
{

    private final static URL PAYMENTEXECUTION_WSDL_LOCATION;
    private final static WebServiceException PAYMENTEXECUTION_EXCEPTION;
    private final static QName PAYMENTEXECUTION_QNAME = new QName("http://bian.com.vn/PaymentExecution/", "PaymentExecution");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.96.23.111:8800/paymentexecution/v1/ws?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PAYMENTEXECUTION_WSDL_LOCATION = url;
        PAYMENTEXECUTION_EXCEPTION = e;
    }

    public PaymentExecution_Service() {
        super(__getWsdlLocation(), PAYMENTEXECUTION_QNAME);
    }

    public PaymentExecution_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), PAYMENTEXECUTION_QNAME, features);
    }

    public PaymentExecution_Service(URL wsdlLocation) {
        super(wsdlLocation, PAYMENTEXECUTION_QNAME);
    }

    public PaymentExecution_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PAYMENTEXECUTION_QNAME, features);
    }

    public PaymentExecution_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PaymentExecution_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PaymentExecution
     */
    @WebEndpoint(name = "PaymentExecutionSOAP")
    public PaymentExecution getPaymentExecutionSOAP() {
        return super.getPort(new QName("http://bian.com.vn/PaymentExecution/", "PaymentExecutionSOAP"), PaymentExecution.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PaymentExecution
     */
    @WebEndpoint(name = "PaymentExecutionSOAP")
    public PaymentExecution getPaymentExecutionSOAP(WebServiceFeature... features) {
        return super.getPort(new QName("http://bian.com.vn/PaymentExecution/", "PaymentExecutionSOAP"), PaymentExecution.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PAYMENTEXECUTION_EXCEPTION!= null) {
            throw PAYMENTEXECUTION_EXCEPTION;
        }
        return PAYMENTEXECUTION_WSDL_LOCATION;
    }

}
