
package org.tempuri;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TrungTamThe", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://10.96.21.155:8080/cntt.asmx?WSDL")
public class TrungTamThe
    extends Service
{

    private final static URL TRUNGTAMTHE_WSDL_LOCATION;
    private final static WebServiceException TRUNGTAMTHE_EXCEPTION;
    private final static QName TRUNGTAMTHE_QNAME = new QName("http://tempuri.org/", "TrungTamThe");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.96.21.155:8080/cntt.asmx?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TRUNGTAMTHE_WSDL_LOCATION = url;
        TRUNGTAMTHE_EXCEPTION = e;
    }

    public TrungTamThe() {
        super(__getWsdlLocation(), TRUNGTAMTHE_QNAME);
    }

    public TrungTamThe(WebServiceFeature... features) {
        super(__getWsdlLocation(), TRUNGTAMTHE_QNAME, features);
    }

    public TrungTamThe(URL wsdlLocation) {
        super(wsdlLocation, TRUNGTAMTHE_QNAME);
    }

    public TrungTamThe(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TRUNGTAMTHE_QNAME, features);
    }

    public TrungTamThe(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TrungTamThe(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TrungTamTheSoap
     */
    @WebEndpoint(name = "TrungTamTheSoap")
    public TrungTamTheSoap getTrungTamTheSoap() {
        return super.getPort(new QName("http://tempuri.org/", "TrungTamTheSoap"), TrungTamTheSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TrungTamTheSoap
     */
    @WebEndpoint(name = "TrungTamTheSoap")
    public TrungTamTheSoap getTrungTamTheSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "TrungTamTheSoap"), TrungTamTheSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TRUNGTAMTHE_EXCEPTION!= null) {
            throw TRUNGTAMTHE_EXCEPTION;
        }
        return TRUNGTAMTHE_WSDL_LOCATION;
    }

}
