
package com.ocb.ttt.ws.service.esb;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Correspondence", targetNamespace = "http://bian.com.vn/Correspondence/", wsdlLocation = "http://10.96.23.111:8800/correspondence/v1/ws?wsdl")
public class Correspondence_Service
    extends Service
{

    private final static URL CORRESPONDENCE_WSDL_LOCATION;
    private final static WebServiceException CORRESPONDENCE_EXCEPTION;
    private final static QName CORRESPONDENCE_QNAME = new QName("http://bian.com.vn/Correspondence/", "Correspondence");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.96.23.111:8800/correspondence/v1/ws?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CORRESPONDENCE_WSDL_LOCATION = url;
        CORRESPONDENCE_EXCEPTION = e;
    }

    public Correspondence_Service() {
        super(__getWsdlLocation(), CORRESPONDENCE_QNAME);
    }

    public Correspondence_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), CORRESPONDENCE_QNAME, features);
    }

    public Correspondence_Service(URL wsdlLocation) {
        super(wsdlLocation, CORRESPONDENCE_QNAME);
    }

    public Correspondence_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CORRESPONDENCE_QNAME, features);
    }

    public Correspondence_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Correspondence_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Correspondence
     */
    @WebEndpoint(name = "CorrespondenceSOAP")
    public Correspondence getCorrespondenceSOAP() {
        return super.getPort(new QName("http://bian.com.vn/Correspondence/", "CorrespondenceSOAP"), Correspondence.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Correspondence
     */
    @WebEndpoint(name = "CorrespondenceSOAP")
    public Correspondence getCorrespondenceSOAP(WebServiceFeature... features) {
        return super.getPort(new QName("http://bian.com.vn/Correspondence/", "CorrespondenceSOAP"), Correspondence.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CORRESPONDENCE_EXCEPTION!= null) {
            throw CORRESPONDENCE_EXCEPTION;
        }
        return CORRESPONDENCE_WSDL_LOCATION;
    }

}
