
package com.com.ttt.sms;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Correspondence", targetNamespace = "http://bian.com.vn/Correspondence/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Correspondence {


    /**
     * 
     * @param parameters
     * @return
     *     returns com.com.ttt.sms.NotifyCorrespondenceSMSOutType
     */
    @WebMethod(action = "http://bian.com.vn/Correspondence/notifyCorrespondenceSMS")
    @WebResult(name = "notifyCorrespondenceSMS_out", targetNamespace = "http://bian.com.vn/Correspondence/", partName = "parameters")
    public NotifyCorrespondenceSMSOutType notifyCorrespondenceSMS(
        @WebParam(name = "notifyCorrespondenceSMS_in", targetNamespace = "http://bian.com.vn/Correspondence/", partName = "parameters")
        NotifyCorrespondenceSMSInType parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.com.ttt.sms.NotifyCorrespondenceEmailOutType
     */
    /*
    @WebMethod(action = "http://bian.com.vn/Correspondence/notifyCorrespondenceEmail")
    @WebResult(name = "notifyCorrespondenceEmail_out", targetNamespace = "http://bian.com.vn/Correspondence/", partName = "parameters")
    public NotifyCorrespondenceEmailOutType notifyCorrespondenceEmail(
        @WebParam(name = "notifyCorrespondenceEmail_in", targetNamespace = "http://bian.com.vn/Correspondence/", partName = "parameters")
        NotifyCorrespondenceEmailInType parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.com.ttt.sms.NotifyCallCenterOutType
     */
    /*
    @WebMethod(action = "http://bian.com.vn/Correspondence/notifyCallCenter")
    @WebResult(name = "notifyCallCenter_out", targetNamespace = "http://bian.com.vn/Correspondence/", partName = "parameters")
    public NotifyCallCenterOutType notifyCallCenter(
        @WebParam(name = "notifyCallCenter_in", targetNamespace = "http://bian.com.vn/Correspondence/", partName = "parameters")
        NotifyCallCenterInType parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.com.ttt.sms.RequestClaimCustomerOutType
     */
    /*
    @WebMethod(action = "http://bian.com.vn/Correspondence/requestClaimCustomer")
    @WebResult(name = "requestClaimCustomer_out", targetNamespace = "http://bian.com.vn/Correspondence/", partName = "parameters")
    public RequestClaimCustomerOutType requestClaimCustomer(
        @WebParam(name = "requestClaimCustomer_in", targetNamespace = "http://bian.com.vn/Correspondence/", partName = "parameters")
        RequestClaimCustomerInType parameters);
    */

}
