
package com.ocb.ttt.soa.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TrungTamTheSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TrungTamTheSoap {


    /**
     * Test any SOA
     * 
     * @param inXml
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SOA_Test_Func", action = "http://tempuri.org/SOA_Test_Func")
    @WebResult(name = "SOA_Test_FuncResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SOA_Test_Func", targetNamespace = "http://tempuri.org/", className = "com.ocb.ttt.soa.webservice.SOATestFunc")
    @ResponseWrapper(localName = "SOA_Test_FuncResponse", targetNamespace = "http://tempuri.org/", className = "com.ocb.ttt.soa.webservice.SOATestFuncResponse")
    public String soaTestFunc(
        @WebParam(name = "in_xml", targetNamespace = "http://tempuri.org/")
        String inXml);

    /**
     * Migration Autho Activity
     * 
     * @return
     *     returns java.lang.String
     */
    /*
    @WebMethod(operationName = "SOA_Migra_Autho_Activity", action = "http://tempuri.org/SOA_Migra_Autho_Activity")
    @WebResult(name = "SOA_Migra_Autho_ActivityResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SOA_Migra_Autho_Activity", targetNamespace = "http://tempuri.org/", className = "com.ocb.ttt.soa.webservice.SOAMigraAuthoActivity")
    @ResponseWrapper(localName = "SOA_Migra_Autho_ActivityResponse", targetNamespace = "http://tempuri.org/", className = "com.ocb.ttt.soa.webservice.SOAMigraAuthoActivityResponse")
    public String soaMigraAuthoActivity();

    /**
     * Lock Card using SOA
     * 
     * @param inCardNbr
     * @param sourceChanel
     * @param inSS
     * @return
     *     returns java.lang.String
     */
    
    @WebMethod(operationName = "SOA_Lock_Card", action = "http://tempuri.org/SOA_Lock_Card")
    @WebResult(name = "SOA_Lock_CardResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SOA_Lock_Card", targetNamespace = "http://tempuri.org/", className = "com.ocb.ttt.soa.webservice.SOALockCard")
    @ResponseWrapper(localName = "SOA_Lock_CardResponse", targetNamespace = "http://tempuri.org/", className = "com.ocb.ttt.soa.webservice.SOALockCardResponse")
    public String soaLockCard(
        @WebParam(name = "source_chanel", targetNamespace = "http://tempuri.org/")
        String sourceChanel,
        @WebParam(name = "in_card_nbr", targetNamespace = "http://tempuri.org/")
        String inCardNbr,
        @WebParam(name = "in_SS", targetNamespace = "http://tempuri.org/")
        String inSS);

    /**
     * Close Account using SOA
     * 
     * @param sourceChanel
     * @param inAccNbr
     * @param reason
     * @param inSS
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SOA_Close_Account", action = "http://tempuri.org/SOA_Close_Account")
    @WebResult(name = "SOA_Close_AccountResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SOA_Close_Account", targetNamespace = "http://tempuri.org/", className = "com.ocb.ttt.soa.webservice.SOACloseAccount")
    @ResponseWrapper(localName = "SOA_Close_AccountResponse", targetNamespace = "http://tempuri.org/", className = "com.ocb.ttt.soa.webservice.SOACloseAccountResponse")
    public String soaCloseAccount(
        @WebParam(name = "source_chanel", targetNamespace = "http://tempuri.org/")
        String sourceChanel,
        @WebParam(name = "in_acc_nbr", targetNamespace = "http://tempuri.org/")
        String inAccNbr,
        @WebParam(name = "reason", targetNamespace = "http://tempuri.org/")
        String reason,
        @WebParam(name = "in_SS", targetNamespace = "http://tempuri.org/")
        String inSS);

    /**
     * Block Unblock Credit Amount...
     * 
     * @param inString
     * @param inAmount
     * @param inMemberId
     * @param inTranscode
     * @param inCrAccountNumber
     * @param inValueAutho
     * @param inValueRef
     * @param inSourcechanel
     * @param inCurrent
     * @return
     *     returns java.lang.String
     */
    /*
    @WebMethod(operationName = "SOA_Block_Unblock_Credit_Amount", action = "http://tempuri.org/SOA_Block_Unblock_Credit_Amount")
    @WebResult(name = "SOA_Block_Unblock_Credit_AmountResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SOA_Block_Unblock_Credit_Amount", targetNamespace = "http://tempuri.org/", className = "com.ocb.ttt.soa.webservice.SOABlockUnblockCreditAmount")
    @ResponseWrapper(localName = "SOA_Block_Unblock_Credit_AmountResponse", targetNamespace = "http://tempuri.org/", className = "com.ocb.ttt.soa.webservice.SOABlockUnblockCreditAmountResponse")
    public String soaBlockUnblockCreditAmount(
        @WebParam(name = "in_string", targetNamespace = "http://tempuri.org/")
        String inString,
        @WebParam(name = "in_transcode", targetNamespace = "http://tempuri.org/")
        String inTranscode,
        @WebParam(name = "in_value_ref", targetNamespace = "http://tempuri.org/")
        String inValueRef,
        @WebParam(name = "in_value_autho", targetNamespace = "http://tempuri.org/")
        String inValueAutho,
        @WebParam(name = "in_cr_account_number", targetNamespace = "http://tempuri.org/")
        String inCrAccountNumber,
        @WebParam(name = "in_member_id", targetNamespace = "http://tempuri.org/")
        String inMemberId,
        @WebParam(name = "in_current", targetNamespace = "http://tempuri.org/")
        String inCurrent,
        @WebParam(name = "in_amount", targetNamespace = "http://tempuri.org/")
        String inAmount,
        @WebParam(name = "in_sourcechanel", targetNamespace = "http://tempuri.org/")
        String inSourcechanel);

    /**
     * Change Contract Status...
     * 
     * @param statusCode
     * @param sourceChanel
     * @param statusName
     * @param inSS
     * @param inContractNbr
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SOA_Change_Contr_Status", action = "http://tempuri.org/SOA_Change_Contr_Status")
    @WebResult(name = "SOA_Change_Contr_StatusResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SOA_Change_Contr_Status", targetNamespace = "http://tempuri.org/", className = "com.ocb.ttt.soa.webservice.SOAChangeContrStatus")
    @ResponseWrapper(localName = "SOA_Change_Contr_StatusResponse", targetNamespace = "http://tempuri.org/", className = "com.ocb.ttt.soa.webservice.SOAChangeContrStatusResponse")
    public String soaChangeContrStatus(
        @WebParam(name = "source_chanel", targetNamespace = "http://tempuri.org/")
        String sourceChanel,
        @WebParam(name = "in_contract_nbr", targetNamespace = "http://tempuri.org/")
        String inContractNbr,
        @WebParam(name = "status_code", targetNamespace = "http://tempuri.org/")
        String statusCode,
        @WebParam(name = "status_name", targetNamespace = "http://tempuri.org/")
        String statusName,
        @WebParam(name = "in_SS", targetNamespace = "http://tempuri.org/")
        String inSS);

    /**
     * Delivery Card using SOA
     * 
     * @param inCardNbr
     * @param sourceChanel
     * @param inSS
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SOA_Delivery_Card", action = "http://tempuri.org/SOA_Delivery_Card")
    @WebResult(name = "SOA_Delivery_CardResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SOA_Delivery_Card", targetNamespace = "http://tempuri.org/", className = "com.ocb.ttt.soa.webservice.SOADeliveryCard")
    @ResponseWrapper(localName = "SOA_Delivery_CardResponse", targetNamespace = "http://tempuri.org/", className = "com.ocb.ttt.soa.webservice.SOADeliveryCardResponse")
    public String soaDeliveryCard(
        @WebParam(name = "source_chanel", targetNamespace = "http://tempuri.org/")
        String sourceChanel,
        @WebParam(name = "in_card_nbr", targetNamespace = "http://tempuri.org/")
        String inCardNbr,
        @WebParam(name = "in_SS", targetNamespace = "http://tempuri.org/")
        String inSS);

    /**
     * Update VIP Flag using SOA
     * 
     * @param inCardNbr
     * @param sourceChanel
     * @param inSS
     * @param type
     * @return
     *     returns java.lang.String
     */
    
    @WebMethod(operationName = "SOA_Update_Vip_Flag", action = "http://tempuri.org/SOA_Update_Vip_Flag")
    @WebResult(name = "SOA_Update_Vip_FlagResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SOA_Update_Vip_Flag", targetNamespace = "http://tempuri.org/", className = "com.ocb.ttt.soa.webservice.SOAUpdateVipFlag")
    @ResponseWrapper(localName = "SOA_Update_Vip_FlagResponse", targetNamespace = "http://tempuri.org/", className = "com.ocb.ttt.soa.webservice.SOAUpdateVipFlagResponse")
    public String soaUpdateVipFlag(
        @WebParam(name = "source_chanel", targetNamespace = "http://tempuri.org/")
        String sourceChanel,
        @WebParam(name = "in_card_nbr", targetNamespace = "http://tempuri.org/")
        String inCardNbr,
        @WebParam(name = "type", targetNamespace = "http://tempuri.org/")
        String type,
        @WebParam(name = "in_SS", targetNamespace = "http://tempuri.org/")
        String inSS);

    /**
     * Update Contract Status using SOA
     * 
     * @param inCardNbr
     * @param sourceChanel
     * @param desc
     * @param inSS
     * @param type
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SOA_Contract_Status", action = "http://tempuri.org/SOA_Contract_Status")
    @WebResult(name = "SOA_Contract_StatusResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SOA_Contract_Status", targetNamespace = "http://tempuri.org/", className = "com.ocb.ttt.soa.webservice.SOAContractStatus")
    @ResponseWrapper(localName = "SOA_Contract_StatusResponse", targetNamespace = "http://tempuri.org/", className = "com.ocb.ttt.soa.webservice.SOAContractStatusResponse")
    public String soaContractStatus(
        @WebParam(name = "source_chanel", targetNamespace = "http://tempuri.org/")
        String sourceChanel,
        @WebParam(name = "in_card_nbr", targetNamespace = "http://tempuri.org/")
        String inCardNbr,
        @WebParam(name = "type", targetNamespace = "http://tempuri.org/")
        String type,
        @WebParam(name = "desc", targetNamespace = "http://tempuri.org/")
        String desc,
        @WebParam(name = "in_SS", targetNamespace = "http://tempuri.org/")
        String inSS);

    /**
     * Update Moto Flag using SOA
     * 
     * @param inCardNbr
     * @param sourceChanel
     * @param inDesc
     * @param inSS
     * @param type
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SOA_Update_Moto_Flag", action = "http://tempuri.org/SOA_Update_Moto_Flag")
    @WebResult(name = "SOA_Update_Moto_FlagResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SOA_Update_Moto_Flag", targetNamespace = "http://tempuri.org/", className = "com.ocb.ttt.soa.webservice.SOAUpdateMotoFlag")
    @ResponseWrapper(localName = "SOA_Update_Moto_FlagResponse", targetNamespace = "http://tempuri.org/", className = "com.ocb.ttt.soa.webservice.SOAUpdateMotoFlagResponse")
    public String soaUpdateMotoFlag(
        @WebParam(name = "source_chanel", targetNamespace = "http://tempuri.org/")
        String sourceChanel,
        @WebParam(name = "in_card_nbr", targetNamespace = "http://tempuri.org/")
        String inCardNbr,
        @WebParam(name = "type", targetNamespace = "http://tempuri.org/")
        String type,
        @WebParam(name = "in_SS", targetNamespace = "http://tempuri.org/")
        String inSS,
        @WebParam(name = "in_desc", targetNamespace = "http://tempuri.org/")
        String inDesc);

    /**
     * Change contract classifers using SOA
     * 
     * @param input
     * @param sourceChanel
     * @param inDesc
     * @param inSS
     * @param inConNbr
     * @return
     *     returns java.lang.String
     */
    /*
    @WebMethod(operationName = "SOA_Update_Contract_Classifiers", action = "http://tempuri.org/SOA_Update_Contract_Classifiers")
    @WebResult(name = "SOA_Update_Contract_ClassifiersResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SOA_Update_Contract_Classifiers", targetNamespace = "http://tempuri.org/", className = "com.ocb.ttt.soa.webservice.SOAUpdateContractClassifiers")
    @ResponseWrapper(localName = "SOA_Update_Contract_ClassifiersResponse", targetNamespace = "http://tempuri.org/", className = "com.ocb.ttt.soa.webservice.SOAUpdateContractClassifiersResponse")
    public String soaUpdateContractClassifiers(
        @WebParam(name = "source_chanel", targetNamespace = "http://tempuri.org/")
        String sourceChanel,
        @WebParam(name = "in_con_nbr", targetNamespace = "http://tempuri.org/")
        String inConNbr,
        @WebParam(name = "input", targetNamespace = "http://tempuri.org/")
        String input,
        @WebParam(name = "in_SS", targetNamespace = "http://tempuri.org/")
        String inSS,
        @WebParam(name = "in_desc", targetNamespace = "http://tempuri.org/")
        String inDesc);

    /**
     * Change contract classifers for related card using SOA
     * 
     * @param input
     * @param sourceChanel
     * @param relationType
     * @param inDesc
     * @param inSS
     * @param inConNbr
     * @return
     *     returns java.lang.String
     */
    /*s
    @WebMethod(operationName = "SOA_Update_Contract_Classifiers_Related_Card", action = "http://tempuri.org/SOA_Update_Contract_Classifiers_Related_Card")
    @WebResult(name = "SOA_Update_Contract_Classifiers_Related_CardResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SOA_Update_Contract_Classifiers_Related_Card", targetNamespace = "http://tempuri.org/", className = "com.ocb.ttt.soa.webservice.SOAUpdateContractClassifiersRelatedCard")
    @ResponseWrapper(localName = "SOA_Update_Contract_Classifiers_Related_CardResponse", targetNamespace = "http://tempuri.org/", className = "com.ocb.ttt.soa.webservice.SOAUpdateContractClassifiersRelatedCardResponse")
    public String soaUpdateContractClassifiersRelatedCard(
        @WebParam(name = "source_chanel", targetNamespace = "http://tempuri.org/")
        String sourceChanel,
        @WebParam(name = "in_con_nbr", targetNamespace = "http://tempuri.org/")
        String inConNbr,
        @WebParam(name = "input", targetNamespace = "http://tempuri.org/")
        String input,
        @WebParam(name = "relation_type", targetNamespace = "http://tempuri.org/")
        String relationType,
        @WebParam(name = "in_SS", targetNamespace = "http://tempuri.org/")
        String inSS,
        @WebParam(name = "in_desc", targetNamespace = "http://tempuri.org/")
        String inDesc);

    /**
     * Card Production using SOA
     * 
     * @param input
     * @param sourceChanel
     * @param inDesc
     * @param inSS
     * @param inConNbr
     * @return
     *     returns java.lang.String
     */
    /*
    @WebMethod(operationName = "SOA_Card_Production", action = "http://tempuri.org/SOA_Card_Production")
    @WebResult(name = "SOA_Card_ProductionResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SOA_Card_Production", targetNamespace = "http://tempuri.org/", className = "com.ocb.ttt.soa.webservice.SOACardProduction")
    @ResponseWrapper(localName = "SOA_Card_ProductionResponse", targetNamespace = "http://tempuri.org/", className = "com.ocb.ttt.soa.webservice.SOACardProductionResponse")
    public String soaCardProduction(
        @WebParam(name = "source_chanel", targetNamespace = "http://tempuri.org/")
        String sourceChanel,
        @WebParam(name = "in_con_nbr", targetNamespace = "http://tempuri.org/")
        String inConNbr,
        @WebParam(name = "input", targetNamespace = "http://tempuri.org/")
        String input,
        @WebParam(name = "in_SS", targetNamespace = "http://tempuri.org/")
        String inSS,
        @WebParam(name = "in_desc", targetNamespace = "http://tempuri.org/")
        String inDesc);

    /**
     * Credit Limit Change using SOA
     * 
     * @param input
     * @param sourceChanel
     * @param inDesc
     * @param inSS
     * @param inConNbr
     * @return
     *     returns java.lang.String
     */
    /*
    @WebMethod(operationName = "SOA_Credit_Limit_Change", action = "http://tempuri.org/SOA_Credit_Limit_Change")
    @WebResult(name = "SOA_Credit_Limit_ChangeResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SOA_Credit_Limit_Change", targetNamespace = "http://tempuri.org/", className = "com.ocb.ttt.soa.webservice.SOACreditLimitChange")
    @ResponseWrapper(localName = "SOA_Credit_Limit_ChangeResponse", targetNamespace = "http://tempuri.org/", className = "com.ocb.ttt.soa.webservice.SOACreditLimitChangeResponse")
    public String soaCreditLimitChange(
        @WebParam(name = "source_chanel", targetNamespace = "http://tempuri.org/")
        String sourceChanel,
        @WebParam(name = "in_con_nbr", targetNamespace = "http://tempuri.org/")
        String inConNbr,
        @WebParam(name = "input", targetNamespace = "http://tempuri.org/")
        String input,
        @WebParam(name = "in_SS", targetNamespace = "http://tempuri.org/")
        String inSS,
        @WebParam(name = "in_desc", targetNamespace = "http://tempuri.org/")
        String inDesc);
*/
    /**
     * Change contract address using SOA
     * 
     * @param input
     * @param sourceChanel
     * @param inDesc
     * @param inSS
     * @param addressType
     * @param inConNbr
     * @return
     *     returns java.lang.String
     */
    /*
    @WebMethod(operationName = "SOA_Update_Contract_Address", action = "http://tempuri.org/SOA_Update_Contract_Address")
    @WebResult(name = "SOA_Update_Contract_AddressResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SOA_Update_Contract_Address", targetNamespace = "http://tempuri.org/", className = "com.ocb.ttt.soa.webservice.SOAUpdateContractAddress")
    @ResponseWrapper(localName = "SOA_Update_Contract_AddressResponse", targetNamespace = "http://tempuri.org/", className = "com.ocb.ttt.soa.webservice.SOAUpdateContractAddressResponse")
    public String soaUpdateContractAddress(
        @WebParam(name = "source_chanel", targetNamespace = "http://tempuri.org/")
        String sourceChanel,
        @WebParam(name = "in_con_nbr", targetNamespace = "http://tempuri.org/")
        String inConNbr,
        @WebParam(name = "input", targetNamespace = "http://tempuri.org/")
        String input,
        @WebParam(name = "in_SS", targetNamespace = "http://tempuri.org/")
        String inSS,
        @WebParam(name = "in_desc", targetNamespace = "http://tempuri.org/")
        String inDesc,
        @WebParam(name = "address_type", targetNamespace = "http://tempuri.org/")
        String addressType);

    /**
     * Change Client Info using SOA
     * 
     * @param input
     * @param sourceChanel
     * @param inDesc
     * @param inSS
     * @param inCIF
     * @return
     *     returns java.lang.String
     */
    /*
    @WebMethod(operationName = "SOA_Update_Client_Info", action = "http://tempuri.org/SOA_Update_Client_Info")
    @WebResult(name = "SOA_Update_Client_InfoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SOA_Update_Client_Info", targetNamespace = "http://tempuri.org/", className = "com.ocb.ttt.soa.webservice.SOAUpdateClientInfo")
    @ResponseWrapper(localName = "SOA_Update_Client_InfoResponse", targetNamespace = "http://tempuri.org/", className = "com.ocb.ttt.soa.webservice.SOAUpdateClientInfoResponse")
    public String soaUpdateClientInfo(
        @WebParam(name = "source_chanel", targetNamespace = "http://tempuri.org/")
        String sourceChanel,
        @WebParam(name = "in_CIF", targetNamespace = "http://tempuri.org/")
        String inCIF,
        @WebParam(name = "input", targetNamespace = "http://tempuri.org/")
        String input,
        @WebParam(name = "in_SS", targetNamespace = "http://tempuri.org/")
        String inSS,
        @WebParam(name = "in_desc", targetNamespace = "http://tempuri.org/")
        String inDesc);

    /**
     * Update SMS Flag using SOA
     * 
     * @param sourceChanel
     * @param mobileNbr
     * @param contractNbr
     * @param inSS
     * @param contractType
     * @param type
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SOA_Update_SMS_Flag", action = "http://tempuri.org/SOA_Update_SMS_Flag")
    @WebResult(name = "SOA_Update_SMS_FlagResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SOA_Update_SMS_Flag", targetNamespace = "http://tempuri.org/", className = "com.ocb.ttt.soa.webservice.SOAUpdateSMSFlag")
    @ResponseWrapper(localName = "SOA_Update_SMS_FlagResponse", targetNamespace = "http://tempuri.org/", className = "com.ocb.ttt.soa.webservice.SOAUpdateSMSFlagResponse")
    public String soaUpdateSMSFlag(
        @WebParam(name = "source_chanel", targetNamespace = "http://tempuri.org/")
        String sourceChanel,
        @WebParam(name = "contract_nbr", targetNamespace = "http://tempuri.org/")
        String contractNbr,
        @WebParam(name = "contract_type", targetNamespace = "http://tempuri.org/")
        String contractType,
        @WebParam(name = "mobile_nbr", targetNamespace = "http://tempuri.org/")
        String mobileNbr,
        @WebParam(name = "type", targetNamespace = "http://tempuri.org/")
        String type,
        @WebParam(name = "in_SS", targetNamespace = "http://tempuri.org/")
        String inSS);

    /**
     * Update ECom Flag using SOA
     * 
     * @param inCardNbr
     * @param sourceChanel
     * @param inSS
     * @param type
     * @return
     *     returns java.lang.String
     */
    
    @WebMethod(operationName = "SOA_Update_ECom_Flag", action = "http://tempuri.org/SOA_Update_ECom_Flag")
    @WebResult(name = "SOA_Update_ECom_FlagResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SOA_Update_ECom_Flag", targetNamespace = "http://tempuri.org/", className = "com.ocb.ttt.soa.webservice.SOAUpdateEComFlag")
    @ResponseWrapper(localName = "SOA_Update_ECom_FlagResponse", targetNamespace = "http://tempuri.org/", className = "com.ocb.ttt.soa.webservice.SOAUpdateEComFlagResponse")
    public String soaUpdateEComFlag(
        @WebParam(name = "source_chanel", targetNamespace = "http://tempuri.org/")
        String sourceChanel,
        @WebParam(name = "in_card_nbr", targetNamespace = "http://tempuri.org/")
        String inCardNbr,
        @WebParam(name = "type", targetNamespace = "http://tempuri.org/")
        String type,
        @WebParam(name = "in_SS", targetNamespace = "http://tempuri.org/")
        String inSS);

    /**
     * Reset Pin try using SOA
     * 
     * @param inCardNbr
     * @param sourceChanel
     * @param inSS
     * @return
     *     returns java.lang.String
     */
    
    @WebMethod(operationName = "SOA_Reset_Pin", action = "http://tempuri.org/SOA_Reset_Pin")
    @WebResult(name = "SOA_Reset_PinResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SOA_Reset_Pin", targetNamespace = "http://tempuri.org/", className = "com.ocb.ttt.soa.webservice.SOAResetPin")
    @ResponseWrapper(localName = "SOA_Reset_PinResponse", targetNamespace = "http://tempuri.org/", className = "com.ocb.ttt.soa.webservice.SOAResetPinResponse")
    public String soaResetPin(
        @WebParam(name = "source_chanel", targetNamespace = "http://tempuri.org/")
        String sourceChanel,
        @WebParam(name = "in_card_nbr", targetNamespace = "http://tempuri.org/")
        String inCardNbr,
        @WebParam(name = "in_SS", targetNamespace = "http://tempuri.org/")
        String inSS);

    /**
     * Update Autopayment using SOA
     * 
     * @param inAutopaymentAcc
     * @param inCrAccountNbr
     * @param sourceChanel
     * @param inSS
     * @param inAutopaymentFlag
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SOA_Update_Autopayment", action = "http://tempuri.org/SOA_Update_Autopayment")
    @WebResult(name = "SOA_Update_AutopaymentResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SOA_Update_Autopayment", targetNamespace = "http://tempuri.org/", className = "com.ocb.ttt.soa.webservice.SOAUpdateAutopayment")
    @ResponseWrapper(localName = "SOA_Update_AutopaymentResponse", targetNamespace = "http://tempuri.org/", className = "com.ocb.ttt.soa.webservice.SOAUpdateAutopaymentResponse")
    public String soaUpdateAutopayment(
        @WebParam(name = "source_chanel", targetNamespace = "http://tempuri.org/")
        String sourceChanel,
        @WebParam(name = "in_cr_account_nbr", targetNamespace = "http://tempuri.org/")
        String inCrAccountNbr,
        @WebParam(name = "in_autopayment_acc", targetNamespace = "http://tempuri.org/")
        String inAutopaymentAcc,
        @WebParam(name = "in_autopayment_flag", targetNamespace = "http://tempuri.org/")
        String inAutopaymentFlag,
        @WebParam(name = "in_SS", targetNamespace = "http://tempuri.org/")
        String inSS);

    /**
     * Misc Credit using SOA
     * 
     * @param sourceChanel
     * @param inAmount
     * @param inDesc
     * @param inAccNbr
     * @param inSS
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SOA_Misc_Credit", action = "http://tempuri.org/SOA_Misc_Credit")
    @WebResult(name = "SOA_Misc_CreditResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SOA_Misc_Credit", targetNamespace = "http://tempuri.org/", className = "com.ocb.ttt.soa.webservice.SOAMiscCredit")
    @ResponseWrapper(localName = "SOA_Misc_CreditResponse", targetNamespace = "http://tempuri.org/", className = "com.ocb.ttt.soa.webservice.SOAMiscCreditResponse")
    public String soaMiscCredit(
        @WebParam(name = "source_chanel", targetNamespace = "http://tempuri.org/")
        String sourceChanel,
        @WebParam(name = "in_acc_nbr", targetNamespace = "http://tempuri.org/")
        String inAccNbr,
        @WebParam(name = "in_amount", targetNamespace = "http://tempuri.org/")
        String inAmount,
        @WebParam(name = "in_desc", targetNamespace = "http://tempuri.org/")
        String inDesc,
        @WebParam(name = "in_SS", targetNamespace = "http://tempuri.org/")
        String inSS);

    /**
     * Issuing Card Using SOA
     * 
     * @param inType
     * @param inParam
     * @param sourceChannel
     * @return
     *     returns java.lang.String
     */
    /*
    @WebMethod(operationName = "SOA_Issuing_Card", action = "http://tempuri.org/SOA_Issuing_Card")
    @WebResult(name = "SOA_Issuing_CardResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SOA_Issuing_Card", targetNamespace = "http://tempuri.org/", className = "com.ocb.ttt.soa.webservice.SOAIssuingCard")
    @ResponseWrapper(localName = "SOA_Issuing_CardResponse", targetNamespace = "http://tempuri.org/", className = "com.ocb.ttt.soa.webservice.SOAIssuingCardResponse")
    public String soaIssuingCard(
        @WebParam(name = "source_channel", targetNamespace = "http://tempuri.org/")
        String sourceChannel,
        @WebParam(name = "in_param", targetNamespace = "http://tempuri.org/")
        String inParam,
        @WebParam(name = "in_type", targetNamespace = "http://tempuri.org/")
        String inType);

    /**
     * List cards of CIF ...
     * 
     * @param cif
     * @return
     *     returns java.lang.String
     */
    /*
    @WebMethod(operationName = "GetInfoCardsByCIF", action = "http://tempuri.org/GetInfoCardsByCIF")
    @WebResult(name = "GetInfoCardsByCIFResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetInfoCardsByCIF", targetNamespace = "http://tempuri.org/", className = "com.ocb.ttt.soa.webservice.GetInfoCardsByCIF")
    @ResponseWrapper(localName = "GetInfoCardsByCIFResponse", targetNamespace = "http://tempuri.org/", className = "com.ocb.ttt.soa.webservice.GetInfoCardsByCIFResponse")
    public String getInfoCardsByCIF(
        @WebParam(name = "cif", targetNamespace = "http://tempuri.org/")
        String cif);

    /**
     * Card Info ...
     * 
     * @param cardNbr
     * @return
     *     returns java.lang.String
     */
    /*
    @WebMethod(operationName = "GetInfoCardByCode", action = "http://tempuri.org/GetInfoCardByCode")
    @WebResult(name = "GetInfoCardByCodeResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetInfoCardByCode", targetNamespace = "http://tempuri.org/", className = "com.ocb.ttt.soa.webservice.GetInfoCardByCode")
    @ResponseWrapper(localName = "GetInfoCardByCodeResponse", targetNamespace = "http://tempuri.org/", className = "com.ocb.ttt.soa.webservice.GetInfoCardByCodeResponse")
    public String getInfoCardByCode(
        @WebParam(name = "card_nbr", targetNamespace = "http://tempuri.org/")
        String cardNbr);

    /**
     * Infos of Source Card and Dest card ...
     * 
     * @param dstCardNbr
     * @param srcCardNbr
     * @return
     *     returns java.lang.String
     */
    /*
    @WebMethod(operationName = "GetInfoCards", action = "http://tempuri.org/GetInfoCards")
    @WebResult(name = "GetInfoCardsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetInfoCards", targetNamespace = "http://tempuri.org/", className = "com.ocb.ttt.soa.webservice.GetInfoCards")
    @ResponseWrapper(localName = "GetInfoCardsResponse", targetNamespace = "http://tempuri.org/", className = "com.ocb.ttt.soa.webservice.GetInfoCardsResponse")
    public String getInfoCards(
        @WebParam(name = "src_card_nbr", targetNamespace = "http://tempuri.org/")
        String srcCardNbr,
        @WebParam(name = "dst_card_nbr", targetNamespace = "http://tempuri.org/")
        String dstCardNbr);

    /**
     * Message confirm about fund transfer ...
     * 
     * @param amount
     * @param srcAccNbr
     * @param trnRefNo
     * @param narrative
     * @param dstCardNbr
     * @return
     *     returns java.lang.String
     */
    /*
    @WebMethod(operationName = "ConfirmTransactionCard", action = "http://tempuri.org/ConfirmTransactionCard")
    @WebResult(name = "ConfirmTransactionCardResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ConfirmTransactionCard", targetNamespace = "http://tempuri.org/", className = "com.ocb.ttt.soa.webservice.ConfirmTransactionCard")
    @ResponseWrapper(localName = "ConfirmTransactionCardResponse", targetNamespace = "http://tempuri.org/", className = "com.ocb.ttt.soa.webservice.ConfirmTransactionCardResponse")
    public String confirmTransactionCard(
        @WebParam(name = "src_acc_nbr", targetNamespace = "http://tempuri.org/")
        String srcAccNbr,
        @WebParam(name = "dst_card_nbr", targetNamespace = "http://tempuri.org/")
        String dstCardNbr,
        @WebParam(name = "amount", targetNamespace = "http://tempuri.org/")
        String amount,
        @WebParam(name = "narrative", targetNamespace = "http://tempuri.org/")
        String narrative,
        @WebParam(name = "trn_ref_no", targetNamespace = "http://tempuri.org/")
        String trnRefNo);

    /**
     * Get current score ...
     * 
     * @param inParameter
     * @return
     *     returns java.lang.String
     */
    /*
    @WebMethod(operationName = "Loyalty_Get_Current_Score", action = "http://tempuri.org/Loyalty_Get_Current_Score")
    @WebResult(name = "Loyalty_Get_Current_ScoreResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Loyalty_Get_Current_Score", targetNamespace = "http://tempuri.org/", className = "com.ocb.ttt.soa.webservice.LoyaltyGetCurrentScore")
    @ResponseWrapper(localName = "Loyalty_Get_Current_ScoreResponse", targetNamespace = "http://tempuri.org/", className = "com.ocb.ttt.soa.webservice.LoyaltyGetCurrentScoreResponse")
    public String loyaltyGetCurrentScore(
        @WebParam(name = "in_parameter", targetNamespace = "http://tempuri.org/")
        String inParameter);

    /**
     * Get gift list ...
     * 
     * @return
     *     returns java.lang.String
     */
    /*
    @WebMethod(operationName = "Loyalty_Get_gift_list", action = "http://tempuri.org/Loyalty_Get_gift_list")
    @WebResult(name = "Loyalty_Get_gift_listResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Loyalty_Get_gift_list", targetNamespace = "http://tempuri.org/", className = "com.ocb.ttt.soa.webservice.LoyaltyGetGiftList")
    @ResponseWrapper(localName = "Loyalty_Get_gift_listResponse", targetNamespace = "http://tempuri.org/", className = "com.ocb.ttt.soa.webservice.LoyaltyGetGiftListResponse")
    public String loyaltyGetGiftList();

    /**
     * Get gift exchange history ...
     * 
     * @param inParameter
     * @return
     *     returns java.lang.String
     */
    /*
    @WebMethod(operationName = "Loyalty_Get_Gift_Exchange_Hist", action = "http://tempuri.org/Loyalty_Get_Gift_Exchange_Hist")
    @WebResult(name = "Loyalty_Get_Gift_Exchange_HistResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Loyalty_Get_Gift_Exchange_Hist", targetNamespace = "http://tempuri.org/", className = "com.ocb.ttt.soa.webservice.LoyaltyGetGiftExchangeHist")
    @ResponseWrapper(localName = "Loyalty_Get_Gift_Exchange_HistResponse", targetNamespace = "http://tempuri.org/", className = "com.ocb.ttt.soa.webservice.LoyaltyGetGiftExchangeHistResponse")
    public String loyaltyGetGiftExchangeHist(
        @WebParam(name = "in_parameter", targetNamespace = "http://tempuri.org/")
        String inParameter);

    /**
     * Check avail score whether adequate for exchanging ...
     * 
     * @param inParameter
     * @return
     *     returns java.lang.String
     */
    /*
    @WebMethod(operationName = "Loyalty_Exchange_Gift", action = "http://tempuri.org/Loyalty_Exchange_Gift")
    @WebResult(name = "Loyalty_Exchange_GiftResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Loyalty_Exchange_Gift", targetNamespace = "http://tempuri.org/", className = "com.ocb.ttt.soa.webservice.LoyaltyExchangeGift")
    @ResponseWrapper(localName = "Loyalty_Exchange_GiftResponse", targetNamespace = "http://tempuri.org/", className = "com.ocb.ttt.soa.webservice.LoyaltyExchangeGiftResponse")
    public String loyaltyExchangeGift(
        @WebParam(name = "in_parameter", targetNamespace = "http://tempuri.org/")
        String inParameter);

    /**
     * Get code for BHD ticket ...
     * 
     * @param inParameter
     * @return
     *     returns java.lang.String
     */
    /*
    @WebMethod(operationName = "Promotion_Get_BHD_Code", action = "http://tempuri.org/Promotion_Get_BHD_Code")
    @WebResult(name = "Promotion_Get_BHD_CodeResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Promotion_Get_BHD_Code", targetNamespace = "http://tempuri.org/", className = "com.ocb.ttt.soa.webservice.PromotionGetBHDCode")
    @ResponseWrapper(localName = "Promotion_Get_BHD_CodeResponse", targetNamespace = "http://tempuri.org/", className = "com.ocb.ttt.soa.webservice.PromotionGetBHDCodeResponse")
    public String promotionGetBHDCode(
        @WebParam(name = "in_parameter", targetNamespace = "http://tempuri.org/")
        String inParameter);

    /**
     * Fast Card Issue
     * 
     * @param inParam
     * @return
     *     returns java.lang.String
     */
    /*
    @WebMethod(operationName = "Fast_Card_Issue", action = "http://tempuri.org/Fast_Card_Issue")
    @WebResult(name = "Fast_Card_IssueResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Fast_Card_Issue", targetNamespace = "http://tempuri.org/", className = "com.ocb.ttt.soa.webservice.FastCardIssue")
    @ResponseWrapper(localName = "Fast_Card_IssueResponse", targetNamespace = "http://tempuri.org/", className = "com.ocb.ttt.soa.webservice.FastCardIssueResponse")
    public String fastCardIssue(
        @WebParam(name = "in_param", targetNamespace = "http://tempuri.org/")
        String inParam);

    /**
     * Update OVD using SOA
     * 
     * @param inIssuingNbr
     * @param sourceChanel
     * @param inSS
     * @param type
     * @return
     *     returns java.lang.String
     */
    /*
    @WebMethod(operationName = "SOA_Update_OVD", action = "http://tempuri.org/SOA_Update_OVD")
    @WebResult(name = "SOA_Update_OVDResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SOA_Update_OVD", targetNamespace = "http://tempuri.org/", className = "com.ocb.ttt.soa.webservice.SOAUpdateOVD")
    @ResponseWrapper(localName = "SOA_Update_OVDResponse", targetNamespace = "http://tempuri.org/", className = "com.ocb.ttt.soa.webservice.SOAUpdateOVDResponse")
    public String soaUpdateOVD(
        @WebParam(name = "source_chanel", targetNamespace = "http://tempuri.org/")
        String sourceChanel,
        @WebParam(name = "in_issuing_nbr", targetNamespace = "http://tempuri.org/")
        String inIssuingNbr,
        @WebParam(name = "type", targetNamespace = "http://tempuri.org/")
        String type,
        @WebParam(name = "in_SS", targetNamespace = "http://tempuri.org/")
        String inSS);

    /**
     * SOA 3D reset SMS OTP ...
     * 
     * @param inCardNbr
     * @param sourceChanel
     * @param inSS
     * @param type
     * @return
     *     returns java.lang.String
     */
    /*
    @WebMethod(operationName = "SOA_Reset_3d_OTP", action = "http://tempuri.org/SOA_Reset_3d_OTP")
    @WebResult(name = "SOA_Reset_3d_OTPResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SOA_Reset_3d_OTP", targetNamespace = "http://tempuri.org/", className = "com.ocb.ttt.soa.webservice.SOAReset3DOTP")
    @ResponseWrapper(localName = "SOA_Reset_3d_OTPResponse", targetNamespace = "http://tempuri.org/", className = "com.ocb.ttt.soa.webservice.SOAReset3DOTPResponse")
    public String soaReset3DOTP(
        @WebParam(name = "source_chanel", targetNamespace = "http://tempuri.org/")
        String sourceChanel,
        @WebParam(name = "in_card_nbr", targetNamespace = "http://tempuri.org/")
        String inCardNbr,
        @WebParam(name = "in_SS", targetNamespace = "http://tempuri.org/")
        String inSS,
        @WebParam(name = "type", targetNamespace = "http://tempuri.org/")
        String type);

    /**
     * SOA Instalment ...
     * 
     * @param inCardNbr
     * @param sourceChanel
     * @param tenor
     * @param tenorCode
     * @param inSS
     * @param docId
     * @return
     *     returns java.lang.String
     */
    /*
    @WebMethod(operationName = "SOA_Instalment", action = "http://tempuri.org/SOA_Instalment")
    @WebResult(name = "SOA_InstalmentResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SOA_Instalment", targetNamespace = "http://tempuri.org/", className = "com.ocb.ttt.soa.webservice.SOAInstalment")
    @ResponseWrapper(localName = "SOA_InstalmentResponse", targetNamespace = "http://tempuri.org/", className = "com.ocb.ttt.soa.webservice.SOAInstalmentResponse")
    public String soaInstalment(
        @WebParam(name = "source_chanel", targetNamespace = "http://tempuri.org/")
        String sourceChanel,
        @WebParam(name = "in_card_nbr", targetNamespace = "http://tempuri.org/")
        String inCardNbr,
        @WebParam(name = "doc_id", targetNamespace = "http://tempuri.org/")
        String docId,
        @WebParam(name = "tenor", targetNamespace = "http://tempuri.org/")
        String tenor,
        @WebParam(name = "tenor_code", targetNamespace = "http://tempuri.org/")
        String tenorCode,
        @WebParam(name = "in_SS", targetNamespace = "http://tempuri.org/")
        String inSS);

    /**
     * Update Retail Oversea transction using SOA
     * 
     * @param inCardNbr
     * @param sourceChanel
     * @param inDesc
     * @param inSS
     * @param type
     * @return
     *     returns java.lang.String
     */
    /*
    @WebMethod(operationName = "SOA_Update_Retail_Oversea", action = "http://tempuri.org/SOA_Update_Retail_Oversea")
    @WebResult(name = "SOA_Update_Retail_OverseaResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SOA_Update_Retail_Oversea", targetNamespace = "http://tempuri.org/", className = "com.ocb.ttt.soa.webservice.SOAUpdateRetailOversea")
    @ResponseWrapper(localName = "SOA_Update_Retail_OverseaResponse", targetNamespace = "http://tempuri.org/", className = "com.ocb.ttt.soa.webservice.SOAUpdateRetailOverseaResponse")
    public String soaUpdateRetailOversea(
        @WebParam(name = "source_chanel", targetNamespace = "http://tempuri.org/")
        String sourceChanel,
        @WebParam(name = "in_card_nbr", targetNamespace = "http://tempuri.org/")
        String inCardNbr,
        @WebParam(name = "type", targetNamespace = "http://tempuri.org/")
        String type,
        @WebParam(name = "in_SS", targetNamespace = "http://tempuri.org/")
        String inSS,
        @WebParam(name = "in_desc", targetNamespace = "http://tempuri.org/")
        String inDesc);
*/

}
