
package com.ocb.ttt.esb.payment;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PaymentExecution", targetNamespace = "http://bian.com.vn/PaymentExecution/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PaymentExecution {


    /**
     * 
     * @param parameters
     * @return
     *     returns com.ocb.ttt.esb.payment.SelectTransactionOutType
     */
    @WebMethod(action = "http://bian.com.vn/PaymentExecution/selectTransaction")
    @WebResult(name = "selectTransaction_out", targetNamespace = "http://bian.com.vn/PaymentExecution/", partName = "parameters")
    public SelectTransactionOutType selectTransaction(
        @WebParam(name = "selectTransaction_in", targetNamespace = "http://bian.com.vn/PaymentExecution/", partName = "parameters")
        SelectTransactionInType parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.ocb.ttt.esb.payment.RetrieveTransactionByIDOutType
     */
    @WebMethod(action = "http://bian.com.vn/PaymentExecution/retrieveTransactionByID")
    @WebResult(name = "retrieveTransactionByID_out", targetNamespace = "http://bian.com.vn/PaymentExecution/", partName = "parameters")
    public RetrieveTransactionByIDOutType retrieveTransactionByID(
        @WebParam(name = "retrieveTransactionByID_in", targetNamespace = "http://bian.com.vn/PaymentExecution/", partName = "parameters")
        RetrieveTransactionByIDInType parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.ocb.ttt.esb.payment.ExecutePaymentInternalOutType
     */
    @WebMethod(action = "http://bian.com.vn/PaymentExecution/executePaymentInternal")
    @WebResult(name = "executePaymentInternal_out", targetNamespace = "http://bian.com.vn/PaymentExecution/", partName = "parameters")
    public ExecutePaymentInternalOutType executePaymentInternal(
        @WebParam(name = "executePaymentInternal_in", targetNamespace = "http://bian.com.vn/PaymentExecution/", partName = "parameters")
        ExecutePaymentInternalInType parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.ocb.ttt.esb.payment.ExecutePaymentExternalOutType
     */
    @WebMethod(action = "http://bian.com.vn/PaymentExecution/executePaymentExternal")
    @WebResult(name = "executePaymentExternal_out", targetNamespace = "http://bian.com.vn/PaymentExecution/", partName = "parameters")
    public ExecutePaymentExternalOutType executePaymentExternal(
        @WebParam(name = "executePaymentExternal_in", targetNamespace = "http://bian.com.vn/PaymentExecution/", partName = "parameters")
        ExecutePaymentExternalInType parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.ocb.ttt.esb.payment.SelectTransactionOperationOutType
     */
    @WebMethod(action = "http://bian.com.vn/PaymentExecution/selectTransactionOperation")
    @WebResult(name = "selectTransactionOperation_out", targetNamespace = "http://bian.com.vn/PaymentExecution/", partName = "parameters")
    public SelectTransactionOperationOutType selectTransactionOperation(
        @WebParam(name = "selectTransactionOperation_in", targetNamespace = "http://bian.com.vn/PaymentExecution/", partName = "parameters")
        SelectTransactionOperationInType parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.ocb.ttt.esb.payment.RetrieveTransactionFeeOutType
     */
    @WebMethod(action = "http://bian.com.vn/PaymentExecution/retrieveTransactionFee")
    @WebResult(name = "retrieveTransactionFee_out", targetNamespace = "http://bian.com.vn/PaymentExecution/", partName = "parameters")
    public RetrieveTransactionFeeOutType retrieveTransactionFee(
        @WebParam(name = "retrieveTransactionFee_in", targetNamespace = "http://bian.com.vn/PaymentExecution/", partName = "parameters")
        RetrieveTransactionFeeInType parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.ocb.ttt.esb.payment.ExecutePaymentFastNapasOutType
     */
    @WebMethod(action = "http://bian.com.vn/PaymentExecution/executePaymentFastNapas")
    @WebResult(name = "executePaymentFastNapas_out", targetNamespace = "http://bian.com.vn/PaymentExecution/", partName = "parameters")
    public ExecutePaymentFastNapasOutType executePaymentFastNapas(
        @WebParam(name = "executePaymentFastNapas_in", targetNamespace = "http://bian.com.vn/PaymentExecution/", partName = "parameters")
        ExecutePaymentFastNapasInType parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.ocb.ttt.esb.payment.ExecutePaymentOutType
     */
    @WebMethod(action = "http://bian.com.vn/PaymentExecution/executePayment")
    @WebResult(name = "executePayment_out", targetNamespace = "http://bian.com.vn/PaymentExecution/", partName = "parameters")
    public ExecutePaymentOutType executePayment(
        @WebParam(name = "executePayment_in", targetNamespace = "http://bian.com.vn/PaymentExecution/", partName = "parameters")
        ExecutePaymentInType parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.ocb.ttt.esb.payment.EvaluateBatchPaymentOutType
     */
    @WebMethod(action = "http://bian.com.vn/PaymentExecution/evaluateBatchPayment")
    @WebResult(name = "evaluateBatchPayment_out", targetNamespace = "http://bian.com.vn/PaymentExecution/", partName = "parameters")
    public EvaluateBatchPaymentOutType evaluateBatchPayment(
        @WebParam(name = "evaluateBatchPayment_in", targetNamespace = "http://bian.com.vn/PaymentExecution/", partName = "parameters")
        EvaluateBatchPaymentInType parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.ocb.ttt.esb.payment.ExecuteBatchPaymentOutType
     */
    @WebMethod(action = "http://bian.com.vn/PaymentExecution/executeBatchPayment")
    @WebResult(name = "executeBatchPayment_out", targetNamespace = "http://bian.com.vn/PaymentExecution/", partName = "parameters")
    public ExecuteBatchPaymentOutType executeBatchPayment(
        @WebParam(name = "executeBatchPayment_in", targetNamespace = "http://bian.com.vn/PaymentExecution/", partName = "parameters")
        ExecuteBatchPaymentInType parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.ocb.ttt.esb.payment.RequestPaymentCancellationOutType
     */
    @WebMethod(action = "http://bian.com.vn/PaymentExecution/requestPaymentCancellation")
    @WebResult(name = "requestPaymentCancellation_out", targetNamespace = "http://bian.com.vn/PaymentExecution/", partName = "parameters")
    public RequestPaymentCancellationOutType requestPaymentCancellation(
        @WebParam(name = "requestPaymentCancellation_in", targetNamespace = "http://bian.com.vn/PaymentExecution/", partName = "parameters")
        RequestPaymentCancellationInType parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.ocb.ttt.esb.payment.RetrieveTransactionOperationOutType
     */
    @WebMethod(action = "http://bian.com.vn/PaymentExecution/retrieveTransactionOperation")
    @WebResult(name = "retrieveTransactionOperation_out", targetNamespace = "http://bian.com.vn/PaymentExecution/", partName = "parameters")
    public RetrieveTransactionOperationOutType retrieveTransactionOperation(
        @WebParam(name = "retrieveTransactionOperation_in", targetNamespace = "http://bian.com.vn/PaymentExecution/", partName = "parameters")
        RetrieveTransactionOperationInType parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.ocb.ttt.esb.payment.ConfigurePaymentOutType
     */
    @WebMethod(action = "http://bian.com.vn/PaymentExecution/configurePayment")
    @WebResult(name = "configurePayment_out", targetNamespace = "http://bian.com.vn/PaymentExecution/", partName = "parameters")
    public ConfigurePaymentOutType configurePayment(
        @WebParam(name = "configurePayment_in", targetNamespace = "http://bian.com.vn/PaymentExecution/", partName = "parameters")
        ConfigurePaymentInType parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.ocb.ttt.esb.payment.RetrievePaymentExecutionApprovalRolesOutType
     */
    @WebMethod(action = "http://bian.com.vn/PaymentExecution/retrievePaymentExecutionApprovalRoles")
    @WebResult(name = "retrievePaymentExecutionApprovalRoles_out", targetNamespace = "http://bian.com.vn/PaymentExecution/", partName = "parameters")
    public RetrievePaymentExecutionApprovalRolesOutType retrievePaymentExecutionApprovalRoles(
        @WebParam(name = "retrievePaymentExecutionApprovalRoles_in", targetNamespace = "http://bian.com.vn/PaymentExecution/", partName = "parameters")
        RetrievePaymentExecutionApprovalRolesInType parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.ocb.ttt.esb.payment.ExecutePaymentCardOutType
     */
    @WebMethod(action = "http://bian.com.vn/PaymentExecution/executePaymentCard")
    @WebResult(name = "executePaymentCard_out", targetNamespace = "http://bian.com.vn/PaymentExecution/", partName = "parameters")
    public ExecutePaymentCardOutType executePaymentCard(
        @WebParam(name = "executePaymentCard_in", targetNamespace = "http://bian.com.vn/PaymentExecution/", partName = "parameters")
        ExecutePaymentCardInType parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.ocb.ttt.esb.payment.ExecutePaymentCardRepaymentOutType
     */
    @WebMethod(action = "http://bian.com.vn/PaymentExecution/executePaymentCardRepayment")
    @WebResult(name = "executePaymentCardRepayment_out", targetNamespace = "http://bian.com.vn/PaymentExecution/", partName = "parameters")
    public ExecutePaymentCardRepaymentOutType executePaymentCardRepayment(
        @WebParam(name = "executePaymentCardRepayment_in", targetNamespace = "http://bian.com.vn/PaymentExecution/", partName = "parameters")
        ExecutePaymentCardRepaymentInType parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.ocb.ttt.esb.payment.RetrieveInsuranceTransactionFeeOutType
     */
    @WebMethod(action = "http://bian.com.vn/PaymentExecution/retrieveInsuranceTransactionFee")
    @WebResult(name = "retrieveInsuranceTransactionFee_out", targetNamespace = "http://bian.com.vn/PaymentExecution/", partName = "parameters")
    public RetrieveInsuranceTransactionFeeOutType retrieveInsuranceTransactionFee(
        @WebParam(name = "retrieveInsuranceTransactionFee_in", targetNamespace = "http://bian.com.vn/PaymentExecution/", partName = "parameters")
        RetrieveInsuranceTransactionFeeInType parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.ocb.ttt.esb.payment.RevertPaymentOutType
     */
    @WebMethod(action = "http://bian.com.vn/PaymentExecution/revertPayment")
    @WebResult(name = "revertPayment_out", targetNamespace = "http://bian.com.vn/PaymentExecution/", partName = "parameters")
    public RevertPaymentOutType revertPayment(
        @WebParam(name = "revertPayment_in", targetNamespace = "http://bian.com.vn/PaymentExecution/", partName = "parameters")
        RevertPaymentInType parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.ocb.ttt.esb.payment.RetrieveLastTransactionOutType
     */
    @WebMethod(action = "http://bian.com.vn/PaymentExecution/retrieveLastTransaction")
    @WebResult(name = "retrieveLastTransaction_out", targetNamespace = "http://bian.com.vn/PaymentExecution/", partName = "parameters")
    public RetrieveLastTransactionOutType retrieveLastTransaction(
        @WebParam(name = "retrieveLastTransaction_in", targetNamespace = "http://bian.com.vn/PaymentExecution/", partName = "parameters")
        RetrieveLastTransactionInType parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.ocb.ttt.esb.payment.SelectFuturePaymentTransactionOutType
     */
    @WebMethod(action = "http://bian.com.vn/PaymentExecution/selectFuturePaymentTransaction")
    @WebResult(name = "selectFuturePaymentTransaction_out", targetNamespace = "http://bian.com.vn/PaymentExecution/", partName = "parameters")
    public SelectFuturePaymentTransactionOutType selectFuturePaymentTransaction(
        @WebParam(name = "selectFuturePaymentTransaction_in", targetNamespace = "http://bian.com.vn/PaymentExecution/", partName = "parameters")
        SelectFuturePaymentTransactionInType parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.ocb.ttt.esb.payment.TerminateFuturePaymentOutType
     */
    @WebMethod(action = "http://bian.com.vn/PaymentExecution/terminateFuturePayment")
    @WebResult(name = "terminateFuturePayment_out", targetNamespace = "http://bian.com.vn/PaymentExecution/", partName = "parameters")
    public TerminateFuturePaymentOutType terminateFuturePayment(
        @WebParam(name = "terminateFuturePayment_in", targetNamespace = "http://bian.com.vn/PaymentExecution/", partName = "parameters")
        TerminateFuturePaymentInType parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.ocb.ttt.esb.payment.ModifyFuturePaymentOutType
     */
    @WebMethod(action = "http://bian.com.vn/PaymentExecution/modifyFuturePayment")
    @WebResult(name = "modifyFuturePayment_out", targetNamespace = "http://bian.com.vn/PaymentExecution/", partName = "parameters")
    public ModifyFuturePaymentOutType modifyFuturePayment(
        @WebParam(name = "modifyFuturePayment_in", targetNamespace = "http://bian.com.vn/PaymentExecution/", partName = "parameters")
        ModifyFuturePaymentInType parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.ocb.ttt.esb.payment.ExecuteRevertPaymentOutType
     */
    @WebMethod(action = "http://bian.com.vn/PaymentExecution/executeRevertPayment")
    @WebResult(name = "executeRevertPayment_out", targetNamespace = "http://bian.com.vn/PaymentExecution/", partName = "parameters")
    public ExecuteRevertPaymentOutType executeRevertPayment(
        @WebParam(name = "executeRevertPayment_in", targetNamespace = "http://bian.com.vn/PaymentExecution/", partName = "parameters")
        ExecuteRevertPaymentInType parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.ocb.ttt.esb.payment.CalculateDiscountAmountOutType
     */
    @WebMethod(action = "http://bian.com.vn/PaymentExecution/calculateDiscountAmount")
    @WebResult(name = "calculateDiscountAmount_out", targetNamespace = "http://bian.com.vn/PaymentExecution/", partName = "parameters")
    public CalculateDiscountAmountOutType calculateDiscountAmount(
        @WebParam(name = "calculateDiscountAmount_in", targetNamespace = "http://bian.com.vn/PaymentExecution/", partName = "parameters")
        CalculateDiscountAmountInType parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.ocb.ttt.esb.payment.SelectBatchTransactionDetailOutType
     */
    @WebMethod(action = "http://bian.com.vn/PaymentExecution/selectBatchTransactionDetail")
    @WebResult(name = "selectBatchTransactionDetail_out", targetNamespace = "http://bian.com.vn/PaymentExecution/", partName = "parameters")
    public SelectBatchTransactionDetailOutType selectBatchTransactionDetail(
        @WebParam(name = "selectBatchTransactionDetail_in", targetNamespace = "http://bian.com.vn/PaymentExecution/", partName = "parameters")
        SelectBatchTransactionDetailInType parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.ocb.ttt.esb.payment.ExecuteCheckingNameBatchPaymentOutType
     */
    @WebMethod(action = "http://bian.com.vn/PaymentExecution/executeCheckingNameBatchPayment")
    @WebResult(name = "executeCheckingNameBatchPayment_out", targetNamespace = "http://bian.com.vn/PaymentExecution/", partName = "parameters")
    public ExecuteCheckingNameBatchPaymentOutType executeCheckingNameBatchPayment(
        @WebParam(name = "executeCheckingNameBatchPayment_in", targetNamespace = "http://bian.com.vn/PaymentExecution/", partName = "parameters")
        ExecuteCheckingNameBatchPaymentInType parameters);

}
